import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Building2, CircleHelp, Flag, Home, Info, PencilLine, ShieldCheck, Sprout, Target, TrendingUp, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { usePlanningPreview } from "@/contexts/PlanningPreview";
import { getDashboard, mxn } from "@/lib/finance/dashboard";
import ProjectionChart from "@/components/dashboard/ProjectionChart";

export default function Dashboard() {
  const { values } = usePlanningPreview();
  const plan = getDashboard(values);
  const date = values.date ? new Date(`${values.date}T00:00:00`) : null;
  const stale = date ? (Date.now() - date.getTime()) / 86400000 > 90 : false;
  const dateLabel = date && Number.isFinite(date.getTime()) ? date.toLocaleDateString('es-MX', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Sin fecha';
  return <div className="min-h-screen pb-24 lg:pb-8">
    <header className="border-b bg-card"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between gap-3 px-5 sm:px-8"><Link to="/" className="flex items-center gap-2 text-primary"><Sprout size={28}/><span className="text-2xl font-semibold tracking-tight">nexus.</span></Link><nav aria-label="Principal" className="hidden items-center gap-8 text-sm lg:flex"><Link to="/inicio" aria-current="page" className="font-semibold text-primary">Inicio</Link><Link to="/datos" className="text-muted-foreground hover:text-primary">Mis datos</Link><a href="#plan" className="text-muted-foreground hover:text-primary">Mi panorama</a></nav><span className="rounded-full bg-secondary px-3 py-2 text-[10px] font-semibold text-primary">VISTA PREVIA</span></div></header>
    <main className="mx-auto max-w-7xl px-5 pt-7 sm:px-8 sm:pt-10">
      <div className="mb-7 flex flex-wrap items-start justify-between gap-5"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Paso 03 · Tu futuro, en perspectiva</p><h1 className="font-editorial text-4xl sm:text-5xl">Tu retiro, con más claridad.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Lo que tienes hoy, lo que necesitas mañana y un siguiente paso que se adapte a tu bolsillo.</p></div><Button asChild className="h-12 rounded-xl px-5"><Link to="/datos">Revisar mi plan <ArrowUpRight className="ml-2" size={17}/></Link></Button></div>
      <div className="mb-7 flex items-start gap-3 rounded-2xl border border-primary/15 bg-secondary/40 p-4 text-xs leading-5"><Info size={18} className="mt-0.5 shrink-0 text-primary"/><p><strong>Una vista para explorar, no una cuenta financiera.</strong> Los datos permanecen solo en memoria y se pierden al recargar. No hay autenticación, guardado, conexión AFORE ni aportaciones reales habilitadas.</p></div>
      {!plan ? <section className="rounded-3xl border bg-card px-6 py-16 text-center"><span className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-secondary text-primary"><Sprout size={40}/></span><h2 className="font-editorial text-3xl">Tu panorama empieza con tus datos.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Agrega saldo y fecha de tu AFORE, ingresos, gastos, edad e ingreso de retiro deseado. No usamos saldos ni movimientos ficticios.</p><Button asChild className="mt-7 h-12 rounded-xl"><Link to="/datos">Completar mis datos <ArrowRight className="ml-2" size={17}/></Link></Button></section> : <>
        <div className="mb-5 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5 text-primary"><PencilLine size={14}/>Datos ingresados por ti · No verificados</span><span className="break-all">{values.afore} · Saldo al {dateLabel}</span>{stale && <span className="rounded-full bg-[hsl(var(--warning))] px-3 py-1 text-[hsl(var(--warning-foreground))]">Más de 90 días: actualiza tu saldo</span>}</div>
        <section aria-label="Resumen de retiro" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[{ title: 'Tu saldo reportado', value: mxn(plan.balance), icon: Wallet, text: 'Ahorro que declaraste en tu AFORE. No cambia al explorar este plan.' }, { title: 'Brecha proyectada', value: mxn(plan.gap), icon: Target, text: 'Lo que faltaría para tu meta al retirarte, con la aportación sugerida. Pesos de hoy.' }, { title: 'Sugerencia mensual', value: mxn(plan.suggestion), icon: TrendingUp, text: 'Estimación basada en tu presupuesto. No es una aportación aceptada ni programada.' }, { title: 'Avance actual a tu meta', value: `${plan.progress.toLocaleString('es-MX', { maximumFractionDigits: 1 })}%`, icon: Flag, text: 'Tu saldo reportado dividido entre el capital objetivo, en pesos de hoy.' }].map(({ title, value, icon: Icon, text }) => <article key={title} className="min-w-0 rounded-2xl border bg-card p-5"><div className="flex items-center justify-between gap-2 text-xs font-medium text-muted-foreground"><h2>{title}</h2><Icon size={17} className="shrink-0 text-primary"/></div><p className="mt-4 break-words text-[28px] font-semibold tracking-tight text-primary">{value}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{text}</p></article>)}
        </section>
        <div id="plan" className="mt-6 grid items-start gap-6 lg:grid-cols-[1.65fr_1fr]">
          <div className="min-w-0 space-y-6"><ProjectionChart plan={plan}/>
            <section className="rounded-3xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-semibold">Tu meta, paso a paso</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Un horizonte de {plan.years} años para retirarte a los {plan.retirementAge}.</p><div className="mt-5 flex flex-wrap justify-between gap-2 text-sm"><span>Capital objetivo</span><strong>{mxn(plan.target)}</strong></div><Progress value={plan.progress} aria-label={`Avance actual: ${plan.progress.toFixed(1)} por ciento`} className="my-3 h-3 bg-secondary"/><div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>Hoy: {mxn(plan.balance)}</span><span>Falta hoy: {mxn(plan.currentGap)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-secondary/50 p-4"><p className="text-xs text-muted-foreground">Ingreso mensual deseado</p><p className="mt-1 text-xl font-semibold text-primary">{mxn(Number(values.desiredIncome))}</p></div><div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">Ingreso mensual estimado</p><p className="mt-1 text-xl font-semibold">{mxn(plan.estimatedIncome)}</p></div></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Ambos en pesos de hoy. Meta = ingreso deseado × 12 × {plan.retirementYears} años de retiro. Ingreso estimado = saldo proyectado ÷ {plan.retirementYears * 12} meses; supone que no hay rendimiento durante el retiro.</p><div className="mt-5 flex gap-3 border-t pt-5"><Flag size={20} className="shrink-0 text-primary"/><div><h3 className="text-sm font-semibold">{plan.progress >= 100 ? 'Tu saldo reportado cubre la meta calculada' : `Siguiente hito: ${Math.min(100, (Math.floor(plan.progress / 25) + 1) * 25)}% de tu meta`}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{plan.progress >= 100 ? 'Revisa tus supuestos y la vigencia del saldo antes de tomar decisiones.' : 'El avance se basa únicamente en tu saldo reportado, no en aportaciones futuras ni en otras metas.'}</p></div></div></section>
            <section className="rounded-3xl border bg-card p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-semibold"><CircleHelp size={19} className="text-primary"/> Cómo calculamos tu panorama</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-xs">{[['Rendimiento nominal anual', '5% supuesto'], ['Inflación anual', '3% supuesta'], ['Duración del retiro', '20 años'], ['Aportación', 'Fija, al final de cada mes']].map(([label, value]) => <div key={label}><dt className="leading-5 text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-6 text-muted-foreground">Capitalización mensual equivalente al 5% anual. La aportación no aumenta con la inflación. No se incluyen comisiones, impuestos, pensiones, aportaciones patronales ni otros ingresos. Los supuestos son ilustrativos, no rendimientos garantizados por tu AFORE ni asesoría individualizada.</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Saldo estimado nominal al retiro: {mxn(plan.nominal)}. Equivalente en pesos de hoy: {mxn(plan.projected)}. La inflación reduce su poder de compra.</p></section>
          </div>
          <div className="min-w-0 space-y-6"><section className="rounded-3xl bg-primary p-6 text-primary-foreground"><span className="text-[10px] font-semibold uppercase tracking-[0.15em]">Un paso posible para ti</span><h2 className="mt-3 font-editorial text-3xl">{plan.suggestion > 0 ? 'Constancia antes que cantidad.' : 'Primero, tu tranquilidad.'}</h2><p className="mt-4 text-4xl font-semibold">{mxn(plan.suggestion)}<span className="text-sm font-normal"> / mes</span></p><p className="mt-4 text-sm leading-6">{plan.suggestion > 0 ? `Tomamos el menor entre 10% de tu ingreso (${mxn(plan.income * 0.1)}) y 50% de tu disponible (${mxn(Math.max(0, plan.available) * 0.5)}), redondeado hacia abajo a pesos completos.` : 'Tu presupuesto no deja margen para sugerir una aportación. Revisa gastos y deudas sin comprometer tus necesidades esenciales.'}</p><p className="mt-3 text-xs leading-5">Esta regla orientativa se recalcula al editar tus datos. No evalúa tu situación financiera completa.</p><Button asChild variant="secondary" className="mt-5 h-12 w-full rounded-xl"><Link to="/datos">Revisar mi presupuesto <ArrowRight className="ml-2" size={16}/></Link></Button></section>
            <section className="rounded-3xl border bg-card p-5 sm:p-6"><h2 className="text-lg font-semibold">Cada peso tiene su lugar</h2><div className="mb-5 mt-2 flex flex-wrap justify-between gap-2 text-sm"><span className="text-muted-foreground">Ingreso mensual</span><strong>{mxn(plan.income)}</strong></div><div className="space-y-4">{[['Gastos esenciales', plan.expenses, 'bg-primary'], ['Pagos de deudas', plan.debts, 'bg-[hsl(var(--chart-amber))]'], ['Reserva de emergencia', plan.buffer, 'bg-[hsl(var(--chart-muted))]'], ['Disponible', Math.max(0, plan.available), 'bg-[hsl(var(--chart-mint))]']].map(([label, amount, color]) => <div key={String(label)}><div className="mb-2 flex flex-wrap justify-between gap-2 text-xs"><span>{label}</span><strong>{mxn(Number(amount))}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted" aria-hidden="true"><div className={`h-full rounded-full ${color}`} style={{ width: `${plan.income > 0 ? Math.min(100, Number(amount) / plan.income * 100) : 0}%` }}/></div></div>)}</div><p className="mt-5 border-t pt-4 text-xs leading-5 text-muted-foreground">Cada barra es una proporción de tu ingreso. Disponible = ingresos − gastos − deudas − reserva.</p>{plan.available < 0 && <p className="mt-3 rounded-xl bg-[hsl(var(--warning))] p-3 text-xs text-[hsl(var(--warning-foreground))]">Déficit mensual: {mxn(-plan.available)}. Tus compromisos superan tus ingresos.</p>}<p className="mt-3 text-xs leading-5">Después de la sugerencia quedarían <strong>{mxn(plan.available - plan.suggestion)}</strong> al mes. No implica una transferencia.</p></section>
            <section className="rounded-3xl border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><Building2 size={18} className="text-primary"/> Estado de tus datos</h2><div className="mt-4 space-y-3 text-xs"><p className="flex justify-between gap-2"><span>Origen</span><strong>Entrada manual</strong></p><p className="flex justify-between gap-2"><span>Saldo efectivo al</span><strong>{dateLabel}</strong></p><p className="flex justify-between gap-2"><span>Conexión AFORE</span><strong>No disponible</strong></p><p className="flex justify-between gap-2"><span>Aportación programada</span><strong>Ninguna</strong></p></div><p className="mt-4 text-xs leading-5 text-muted-foreground">No verificamos tus datos con terceros. Actualízalos si cambian tus ingresos, gastos o saldo.</p></section>
            <section className="rounded-3xl border border-dashed bg-card/50 p-5"><h2 className="font-semibold">Actividad reciente</h2><p className="mt-3 text-sm text-muted-foreground">Sin movimientos guardados.</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Revisar una proyección no crea una aportación. No hay contribuciones confirmadas por un proveedor ni cambios de plan persistidos.</p><div className="mt-4 flex items-start gap-2 text-xs text-primary"><ShieldCheck size={17} className="shrink-0"/>Aportaciones reales próximamente. No se ha movido dinero.</div></section>
          </div>
        </div>
      </>}
      <p className="py-8 text-center text-xs leading-5 text-muted-foreground">Nexus · Planea con información, decide con calma.<br/>Estimaciones ilustrativas. Todos los importes en MXN.</p>
    </main>
    <nav aria-label="Navegación móvil" className="fixed inset-x-0 bottom-0 z-20 flex justify-around border-t bg-card px-4 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-3 lg:hidden"><Link to="/inicio" aria-current="page" className="flex min-h-11 flex-col items-center gap-1 px-5 text-[10px] font-semibold text-primary"><Home size={20}/>Inicio</Link><Link to="/datos" className="flex min-h-11 flex-col items-center gap-1 px-5 text-[10px] text-muted-foreground"><PencilLine size={20}/>Mis datos</Link><Link to="/" className="flex min-h-11 flex-col items-center gap-1 px-5 text-[10px] text-muted-foreground"><ShieldCheck size={20}/>Acceso</Link></nav>
  </div>;
}
