import { useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Building2, Check, CheckCircle2, Info, LockKeyhole, PencilLine, ShieldCheck, Sprout } from "lucide-react";
import { Button } from "@/components/ui/button";
import { usePlanningPreview } from "@/contexts/PlanningPreview";
import { getDashboard, mxn } from "@/lib/finance/dashboard";
import { projectScenario } from "@/lib/finance/scenarios";

const percent = (value: number) => new Intl.NumberFormat('es-MX', { style: 'percent', maximumFractionDigits: 2 }).format(value);

export default function PlanReview() {
  const { values, reviewSelection, setReviewSelection } = usePlanningPreview();
  const plan = getDashboard(values);
  const sourceKey = JSON.stringify(values);
  const selection = reviewSelection?.sourceKey === sourceKey ? reviewSelection : null;
  const scenario = selection?.scenario;
  const projection = scenario ? projectScenario(scenario) : null;
  const valid = !!(plan && scenario && projection && Number.isSafeInteger(scenario.monthly) && scenario.monthly <= plan.suggestion && scenario.balance === plan.balance && scenario.age === plan.age);
  const confirmed = valid && selection?.confirmed;
  const successRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (confirmed) successRef.current?.focus(); }, [confirmed]);
  const confirm = () => {
    if (!valid || confirmed) return;
    setReviewSelection(previous => previous && previous.sourceKey === sourceKey ? { ...previous, confirmed: true } : previous);
  };

  return <div className="min-h-screen pb-10"><header className="border-b bg-card"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between gap-3 px-5 sm:px-8"><Link to="/inicio" className="flex items-center gap-2 text-primary"><Sprout size={28}/><span className="text-2xl font-semibold tracking-tight">nexus.</span></Link><span className="rounded-full bg-secondary px-3 py-2 text-[10px] font-semibold text-primary">VISTA PREVIA · SIN PAGOS</span></div></header>
    <main className="mx-auto max-w-6xl px-5 pt-5 sm:px-8 sm:pt-8"><Link to="/simulador" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-primary"><ArrowLeft size={17}/> Volver al simulador</Link>
      <div className="mb-7 mt-5"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Paso 06 · Revisión y confirmación</p><h1 className="font-editorial text-4xl leading-tight sm:text-5xl">Un último vistazo.<br/><span className="italic text-primary">La decisión es tuya.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Revisa el monto, el destino previsto y los supuestos antes de confirmar tu elección para esta vista previa.</p></div>
      {!valid || !plan || !scenario || !projection ? <section className="rounded-3xl border bg-card p-8 text-center"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-secondary text-primary"><PencilLine size={28}/></div><h2 className="text-xl font-semibold">{reviewSelection ? 'Tu escenario necesita una nueva revisión' : 'Primero, elige un escenario'}</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">{reviewSelection ? 'Tus datos cambiaron o el monto ya no cumple el límite orientativo. Vuelve a simular antes de confirmar; no ajustaremos tu elección automáticamente.' : 'Selecciona un escenario dentro de tu presupuesto en el simulador. Si recargaste la página, vuelve a ingresar tus datos: no se guardan en una cuenta.'}</p><Button asChild className="mt-6 h-12 rounded-xl"><Link to={plan ? '/simulador' : '/datos'}>{plan ? 'Revisar mi escenario' : 'Completar mis datos'}<ArrowRight size={17} className="ml-2"/></Link></Button></section> : <>
        {confirmed && <section role="status" className="mb-6 rounded-3xl border border-primary/20 bg-secondary/70 p-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 shrink-0 text-primary" size={28}/><div><h2 ref={successRef} tabIndex={-1} className="font-editorial text-2xl text-primary focus:outline-none">Tu elección quedó confirmada en esta vista.</h2><p className="mt-2 text-sm leading-6">{scenario.monthly === 0 ? 'Elegiste continuar sin aportación.' : `Elegiste explorar ${mxn(scenario.monthly)} al mes.`} No se ha guardado un plan, autorizado un cargo ni enviado dinero a tu AFORE.</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Este estado es temporal y se pierde al recargar. No es un comprobante de pago.</p></div></div></section>}
        <div className="grid items-start gap-6 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="space-y-6"><section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">El escenario que elegiste</h2><span className="rounded-full bg-secondary px-3 py-1.5 text-[10px] font-semibold text-primary">{confirmed ? 'REVISADO' : 'POR REVISAR'}</span></div><div className="my-6 border-y py-6"><p className="text-xs text-muted-foreground">Aportación mensual propuesta</p><p className="mt-2 break-words text-4xl font-semibold tracking-tight text-primary sm:text-5xl">{mxn(scenario.monthly)}<span className="ml-2 text-sm font-normal">MXN / mes</span></p><p className="mt-3 text-xs leading-5 text-muted-foreground">{scenario.monthly === 0 ? 'Sin aportación nueva; la proyección usa solo tu saldo reportado.' : 'Frecuencia mensual para calcular tu escenario. No hay cobros recurrentes programados.'}</p></div><div className="flex items-start gap-3 rounded-2xl bg-background p-4"><span className="rounded-xl bg-secondary p-3 text-primary"><Building2 size={21}/></span><div className="min-w-0"><p className="text-xs text-muted-foreground">Destino previsto, no conectado</p><h3 className="mt-1 break-words font-semibold">{values.afore}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Nombre ingresado por ti. No se ha verificado una cuenta receptora.</p></div></div><dl className="mt-5 space-y-4 text-sm">{[
            ['Edad de retiro', `${scenario.retirementAge} años`],
            ['Horizonte de ahorro', `${scenario.retirementAge - scenario.age} años`],
            ['Comisión anual sobre saldo', percent(scenario.annualFee)],
            ['Rendimiento bruto anual supuesto', percent(scenario.annualReturn)],
            ['Inflación anual supuesta', percent(scenario.inflation)],
            ['Duración estimada del retiro', `${scenario.retirementYears} años`],
          ].map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2"><dt className="text-muted-foreground">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl><Button asChild variant="outline" className="mt-6 h-12 w-full rounded-xl"><Link to="/simulador"><PencilLine size={16} className="mr-2"/>Editar monto o supuestos</Link></Button></section>
            <section className="rounded-3xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-semibold">Lo que este escenario estima</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">Saldo neto al retiro</p><p className="mt-2 break-words text-2xl font-semibold text-primary">{mxn(projection.real)}</p><p className="mt-1 text-xs text-muted-foreground">En pesos de hoy, después de comisión</p></div><div className="rounded-2xl bg-muted p-4"><p className="text-xs text-muted-foreground">Ingreso mensual estimado</p><p className="mt-2 break-words text-2xl font-semibold">{mxn(projection.monthlyIncome)}</p><p className="mt-1 text-xs text-muted-foreground">En pesos de hoy, durante {scenario.retirementYears} años</p></div></div><p className="mt-4 text-xs leading-6 text-muted-foreground">Equivalente nominal al retiro: {mxn(projection.nominal)}. El impacto de la comisión sobre el saldo final sería {mxn(projection.feeImpactReal)} en pesos de hoy, incluyendo el crecimiento que deja de generarse.</p><details className="mt-4 text-xs"><summary className="cursor-pointer py-3 font-medium text-primary">Revisar el cálculo y sus límites</summary><p className="leading-6 text-muted-foreground">Cada mes aplicamos el rendimiento anual equivalente, descontamos la comisión anual dividida entre 12 del saldo que creció y agregamos la aportación al final del mes. La comisión es un supuesto personalizable, no una tarifa verificada. Las aportaciones no aumentan con inflación. El ingreso de retiro divide el saldo real entre {scenario.retirementYears * 12} meses, sin rendimientos ni comisiones durante el retiro. Excluimos impuestos, beneficios fiscales, pensión pública y otros aportes. No es un rendimiento garantizado ni asesoría individualizada.</p></details></section>
          </div>
          <div className="space-y-5"><section className="rounded-3xl bg-primary p-6 text-primary-foreground"><span className="text-[10px] font-semibold uppercase tracking-[0.15em]">Antes de dar el siguiente paso</span><h2 className="mt-3 font-editorial text-3xl">Tu presupuesto, primero.</h2><dl className="mt-6 space-y-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><dt>Disponible antes de aportar</dt><dd className="font-semibold">{mxn(plan.available)}</dd></div><div className="flex flex-wrap justify-between gap-2"><dt>Monto elegido</dt><dd className="font-semibold">{mxn(scenario.monthly)}</dd></div><div className="flex flex-wrap justify-between gap-2 border-t border-primary-foreground/25 pt-4"><dt>Margen restante estimado</dt><dd className="font-semibold">{mxn(plan.available - scenario.monthly)}</dd></div></dl><p className="mt-5 flex gap-2 text-xs leading-5"><ShieldCheck size={18} className="shrink-0"/>{plan.available <= 0 ? 'No tienes margen positivo. Esta elección de $0 no resuelve un posible déficit; revisa tu presupuesto antes de aportar.' : `Dentro del máximo orientativo de ${mxn(plan.suggestion)}. Tus gastos, deudas y reserva ya se descontaron para calcular el disponible.`}</p></section>
            <section className="rounded-3xl border bg-card p-5 sm:p-6"><h2 className="text-lg font-semibold">Qué estás confirmando</h2><ul className="mt-4 space-y-3 text-xs leading-5">{['He revisado el monto y los supuestos de este escenario.', 'Entiendo que solo se confirma una elección temporal.', 'No autorizo cargos, transferencias ni pagos recurrentes.'].map(text => <li key={text} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-primary"/>{text}</li>)}</ul><p id="confirmation-scope" className="mt-4 rounded-xl bg-[hsl(var(--warning))] p-3 text-xs leading-5 text-[hsl(var(--warning-foreground))]">El botón no guarda un plan ni crea una aportación. No modifica el saldo reportado de {mxn(plan.balance)}.</p><Button type="button" onClick={confirm} disabled={!!confirmed} aria-describedby="confirmation-scope" className="mt-5 h-auto min-h-12 w-full whitespace-normal rounded-xl px-4 py-3">{confirmed ? 'Elección confirmada · Solo vista previa' : scenario.monthly === 0 ? 'Confirmar vista previa sin aportación' : 'Confirmar elección · Solo vista previa'}{confirmed ? <CheckCircle2 size={17} className="ml-2 shrink-0"/> : <ArrowRight size={17} className="ml-2 shrink-0"/>}</Button>{confirmed && <Button asChild variant="outline" className="mt-3 h-12 w-full rounded-xl"><Link to="/inicio">Volver a mi panorama</Link></Button>}<p className="mt-3 text-center text-[11px] leading-5 text-muted-foreground">{confirmed ? 'El panorama inicial conserva sus supuestos originales.' : 'Un toque confirma solo lo que acabas de revisar.'}</p></section>
            <aside className="rounded-2xl border border-dashed p-5"><h2 className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole size={17} className="text-primary"/>Aportaciones reales próximamente</h2><p className="mt-3 text-xs leading-6 text-muted-foreground">Guardar un plan requiere una cuenta y una base de datos configuradas. Aportar dinero requiere una integración AFORE validada y una autorización independiente. No hay cargos pendientes ni aportaciones confirmadas por un proveedor.</p></aside>
          </div>
        </div>
        <div className="mt-6 flex gap-3 rounded-2xl bg-secondary/40 p-4 text-xs leading-5 text-muted-foreground"><Info size={18} className="shrink-0 text-primary"/><p>Origen: datos ingresados por ti, no verificados. Saldo efectivo al {new Date(`${values.date}T00:00:00`).toLocaleDateString('es-MX')}. Confirma que tu presupuesto y tu saldo sigan vigentes antes de tomar decisiones reales.</p></div>
      </>}
    </main>
  </div>;
}
