import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Info, ShieldCheck, SlidersHorizontal, Sprout, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { usePlanningPreview } from "@/contexts/PlanningPreview";
import { futureBalance, getDashboard, mxn } from "@/lib/finance/dashboard";

export default function Recommendation() {
  const { values } = usePlanningPreview();
  const plan = getDashboard(values);
  return <div className="min-h-screen pb-10"><header className="border-b bg-card"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5 sm:px-8"><Link to="/inicio" className="flex items-center gap-2 text-primary"><Sprout size={28}/><span className="text-2xl font-semibold tracking-tight">nexus.</span></Link><span className="rounded-full bg-secondary px-3 py-2 text-[10px] font-semibold text-primary">VISTA PREVIA</span></div></header><main className="mx-auto max-w-6xl px-5 pt-5 sm:px-8 sm:pt-8"><Link to="/inicio" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-primary"><ArrowLeft size={17}/> Volver a mi panorama</Link><p className="mb-3 mt-5 text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Paso 04 · Tu recomendación</p><h1 className="font-editorial text-4xl leading-tight sm:text-5xl">Un monto que se adapte<br/><span className="italic text-primary">a tu vida de hoy.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Entiende de dónde sale la sugerencia, revisa tu margen y elige una cantidad sin descuidar lo esencial.</p>
    {!plan ? <section className="mt-7 rounded-3xl border bg-card p-8 text-center"><Wallet className="mx-auto mb-4 text-primary" size={36}/><h2 className="text-xl font-semibold">Primero, conozcamos tu presupuesto</h2><p className="mt-3 text-sm text-muted-foreground">Completa tus datos para obtener una sugerencia. No utilizamos cifras ficticias.</p><Button asChild className="mt-5 h-12 rounded-xl"><Link to="/datos">Agregar mis datos <ArrowRight className="ml-2" size={17}/></Link></Button></section> : <RecommendationDetails key={JSON.stringify(values)} plan={plan}/>}
    <p className="mt-8 text-center text-xs leading-5 text-muted-foreground">Datos ingresados por ti, no verificados. No es asesoría financiera individualizada.<br/>Sin guardado ni pagos: la elección se pierde al salir de esta pantalla.</p>
  </main></div>;
}

function RecommendationDetails({ plan }: { plan: NonNullable<ReturnType<typeof getDashboard>> }) {
  const [input, setInput] = useState(String(plan.suggestion));
  const [accepted, setAccepted] = useState<number | null>(null);
  const amount = Number(input);
  const valid = input.trim() !== "" && Number.isSafeInteger(amount) && amount >= 0 && amount <= 1e9;
  const aboveLimit = valid && amount > plan.suggestion;
  const allowed = valid && !aboveLimit;
  const update = (value: string) => { setInput(value); setAccepted(null); };
  const projected = allowed ? futureBalance(plan.balance, amount, plan.years, plan.annualReturn) / Math.pow(1 + plan.inflation, plan.years) : null;
  const allocation = [
    { label: 'Gastos esenciales', amount: plan.expenses, color: 'bg-primary' },
    { label: 'Pagos de deudas', amount: plan.debts, color: 'bg-[hsl(var(--chart-amber))]' },
    { label: 'Reserva de emergencia', amount: plan.buffer, color: 'bg-[hsl(var(--chart-muted))]' },
    { label: 'Disponible antes de aportar', amount: Math.max(0, plan.available), color: 'bg-[hsl(var(--chart-mint))]' },
  ];
  return <>
    <div className="mt-7 grid items-start gap-6 lg:grid-cols-[1.1fr_1fr]">
      <div className="space-y-6"><section className="rounded-3xl bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex items-center gap-2 text-xs"><Sprout size={18}/> Sugerencia basada en tu presupuesto</div><p className="mt-5 break-words text-5xl font-semibold tracking-tight">{mxn(plan.suggestion)}<span className="ml-2 text-sm font-normal">MXN / mes</span></p><h2 className="mt-5 font-editorial text-2xl">{plan.suggestion > 0 ? 'Avanza sin quedarte sin margen.' : 'Cuidar tu presente también es avanzar.'}</h2><p className="mt-3 text-sm leading-6">{plan.suggestion > 0 ? 'Esta regla conserva al menos la mitad de tu disponible y limita la sugerencia al 10% de tu ingreso. Puedes elegir una cantidad menor, incluso cero.' : 'No sugerimos aportar con el margen actual. Revisa tu presupuesto antes de asumir otro compromiso; no necesitas aportar para explorar tu plan.'}</p></section>
        <section className="rounded-3xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-semibold">¿Cómo llegamos a este monto?</h2><ol className="mt-5 space-y-5">{[
          ['Partimos de tu ingreso', `${mxn(plan.income)} netos al mes, según lo que ingresaste.`],
          ['Protegemos tus compromisos', `${mxn(plan.expenses)} de gastos + ${mxn(plan.debts)} de deudas + ${mxn(plan.buffer)} de reserva.`],
          ['Calculamos tu disponible', `${mxn(plan.income)} − ${mxn(plan.expenses + plan.debts + plan.buffer)} = ${mxn(plan.available)} al mes.`],
          ['Aplicamos un límite prudente', `El menor entre 10% del ingreso (${mxn(plan.income * 0.1)}) y 50% del disponible positivo (${mxn(Math.max(0, plan.available) * 0.5)}). Redondeamos hacia abajo a pesos completos: ${mxn(plan.suggestion)}.`],
        ].map(([title, text], index) => <li key={title} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-semibold text-primary">{index + 1}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></li>)}</ol><p className="mt-5 rounded-xl bg-muted p-3 text-xs leading-5 text-muted-foreground">La sugerencia y el máximo permitido en esta vista usan la misma regla. Se recalculan al cambiar tus datos; no garantizan que alcances tu meta de retiro.</p></section>
        <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Tu presupuesto, visible</h2><Wallet size={20} className="text-primary"/></div><p className="mt-2 text-xs text-muted-foreground">Cada barra muestra una proporción de tu ingreso mensual.</p><div className="mt-5 space-y-4">{allocation.map(item => <div key={item.label}><div className="mb-2 flex flex-wrap justify-between gap-2 text-xs"><span>{item.label}</span><strong>{mxn(item.amount)}</strong></div><div aria-hidden="true" className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${item.color}`} style={{ width: `${plan.income > 0 ? Math.min(100, item.amount / plan.income * 100) : 0}%` }}/></div></div>)}</div>{plan.available < 0 && <p className="mt-4 text-sm font-medium text-destructive">Déficit mensual: {mxn(-plan.available)}. Prioriza revisar tu presupuesto.</p>}<Button asChild variant="outline" className="mt-5 h-11 w-full rounded-xl"><Link to="/datos">Editar ingresos y gastos</Link></Button></section>
      </div>
      <section className="min-w-0 rounded-3xl border bg-card p-5 sm:p-7" aria-labelledby="adjust-title"><div className="flex items-center gap-3"><span className="rounded-xl bg-secondary p-3 text-primary"><SlidersHorizontal size={22}/></span><div><h2 id="adjust-title" className="text-lg font-semibold">Tú eliges el monto</h2><p className="text-xs text-muted-foreground">Un ajuste, no una obligación.</p></div></div><form onSubmit={event => { event.preventDefault(); if (allowed) setAccepted(amount); }} className="mt-6 space-y-5">
        <div className="space-y-2"><Label htmlFor="monthly-amount">Aportación mensual para explorar (MXN)</Label><div className="relative"><span className="absolute left-4 top-4 text-muted-foreground" aria-hidden="true">$</span><Input id="monthly-amount" type="number" inputMode="numeric" min="0" max={plan.suggestion} step="1" required value={input} onChange={event => update(event.target.value)} aria-invalid={!allowed} aria-describedby="amount-help amount-status" className="h-14 rounded-xl pl-9 text-2xl font-semibold text-primary"/></div><p id="amount-help" className="text-xs leading-5 text-muted-foreground">Pesos completos. Máximo orientativo: {mxn(plan.suggestion)} al mes.</p></div>
        <Slider aria-label="Aportación mensual para explorar" min={0} max={Math.max(1, plan.suggestion)} step={1} disabled={plan.suggestion === 0} value={[valid ? Math.min(amount, plan.suggestion) : 0]} onValueChange={([value]) => update(String(value))} className="py-3"/><div className="!mt-1 flex justify-between text-xs text-muted-foreground"><span>$0</span><span>{mxn(plan.suggestion)}</span></div>
        <div id="amount-status" role="status" className={`rounded-xl p-4 text-xs leading-5 ${allowed ? 'bg-secondary/60 text-primary' : 'bg-[hsl(var(--warning))] text-[hsl(var(--warning-foreground))]'}`}>
          {!valid ? 'Ingresa un monto válido en pesos completos, igual o mayor que cero.' : aboveLimit ? <><strong>Este monto supera el límite orientativo.</strong><p className="mt-1">Para mantener el margen de tu presupuesto, elige {mxn(plan.suggestion)} o menos. No hemos cambiado tu monto.</p><Button type="button" variant="outline" onClick={() => update(String(plan.suggestion))} className="mt-3 h-auto min-h-11 w-full whitespace-normal rounded-xl bg-card py-2 text-primary">Usar {mxn(plan.suggestion)} como monto</Button></> : <><strong>{amount === 0 ? 'Sin aportación por ahora.' : 'Dentro del límite orientativo.'}</strong><p className="mt-1">{plan.available < 0 ? 'Tu presupuesto tiene un déficit. Revisa tus compromisos antes de aportar.' : `Después de este monto quedarían ${mxn(plan.available - amount)} disponibles al mes, además de tu reserva de emergencia.`}</p></>}
        </div>
        {projected !== null && <div className="space-y-3 border-y py-5"><h3 className="text-sm font-semibold">¿Qué significaría para tu retiro?</h3><div className="flex flex-wrap justify-between gap-2 text-xs"><span className="text-muted-foreground">Saldo estimado a los {plan.retirementAge} años</span><strong>{mxn(projected)}</strong></div><div className="flex flex-wrap justify-between gap-2 text-xs"><span className="text-muted-foreground">Ingreso mensual estimado durante 20 años</span><strong>{mxn(projected / 240)}</strong></div><p className="text-xs leading-5 text-muted-foreground">Pesos de hoy. Supone 5% de rendimiento nominal anual, 3% de inflación y aportaciones fijas al final de cada mes. Esta vista rápida excluye impuestos y comisiones; el siguiente simulador permite personalizar la comisión. Supone rendimiento cero durante el retiro. No son resultados garantizados.</p></div>}
        <Button type="submit" disabled={!allowed || accepted === amount} className="h-auto min-h-12 w-full whitespace-normal rounded-xl px-4 py-3">{accepted === amount ? 'Monto elegido para esta vista' : amount === 0 && allowed ? 'Continuar sin aportación en esta vista' : 'Aceptar monto para esta vista'}<ArrowRight size={17} className="ml-2 shrink-0"/></Button>
        {accepted !== null && <div role="status" className="rounded-xl border border-primary/20 bg-secondary/40 p-4"><div className="flex items-start gap-2 text-sm font-semibold text-primary"><CheckCircle2 size={19} className="shrink-0"/>Elegiste {mxn(accepted)} al mes para explorar.</div><p className="mt-2 text-xs leading-5 text-muted-foreground">No se guardó un plan ni se programó una aportación. El saldo de tu AFORE no cambia. Puedes ajustar el monto y aceptarlo de nuevo.</p></div>}
        {accepted !== null && <Button asChild variant="secondary" className="h-12 w-full rounded-xl"><Link to="/simulador" state={{ monthly: accepted }}>Simular mi retiro y comisiones <ArrowRight size={17} className="ml-2"/></Link></Button>}
        <p className="flex gap-2 text-xs leading-5 text-muted-foreground"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-primary"/>Aceptar aquí solo confirma tu elección en esta pantalla. No autoriza pagos ni conexiones con tu AFORE.</p>
      </form></section>
    </div>
    <aside className="mt-6 flex gap-3 rounded-2xl bg-[hsl(var(--warning))] p-4 text-xs leading-5 text-[hsl(var(--warning-foreground))]"><Info size={18} className="mt-0.5 shrink-0"/><p><strong>Aportaciones reales no disponibles.</strong> Esta es una regla orientativa basada exclusivamente en tus datos manuales. Si tu ingreso es variable, tus datos están desactualizados o faltan gastos, revisa tu presupuesto antes de tomar decisiones.</p></aside>
  </>;
}
