import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { ArrowLeft, Info, Plus, RotateCcw, Sprout, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { usePlanningPreview } from "@/contexts/PlanningPreview";
import { getDashboard, mxn } from "@/lib/finance/dashboard";
import { projectScenario, type ScenarioInput } from "@/lib/finance/scenarios";
import ScenarioChart from "@/components/planning/ScenarioChart";

type Plan = NonNullable<ReturnType<typeof getDashboard>>;
type Fields = { monthly: string; retirementAge: string; annualReturn: string; inflation: string; annualFee: string; retirementYears: string };
type Comparison = { id: number; fields: Fields; real: number; income: number; delta: number };

export default function Simulator() {
  const { values } = usePlanningPreview();
  const plan = getDashboard(values);
  const location = useLocation();
  const incoming: unknown = location.state?.monthly;
  const initial = plan && typeof incoming === 'number' && Number.isSafeInteger(incoming) && incoming >= 0 && incoming <= plan.suggestion ? incoming : plan?.suggestion ?? 0;
  return <div className="min-h-screen pb-10"><header className="border-b bg-card"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/inicio" className="flex items-center gap-2 text-primary"><Sprout size={28}/><span className="text-2xl font-semibold tracking-tight">nexus.</span></Link><span className="rounded-full bg-secondary px-3 py-2 text-[10px] font-semibold text-primary">SIMULACIÓN · SIN GUARDAR</span></div></header><main className="mx-auto max-w-7xl px-5 pt-5 sm:px-8"><Link to="/recomendacion" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-primary"><ArrowLeft size={17}/> Volver a mi recomendación</Link><p className="mb-3 mt-5 text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Paso 05 · Simulador de retiro</p><h1 className="font-editorial text-4xl sm:text-5xl">¿Y si tu futuro<br/><span className="italic text-primary">empieza con otro paso?</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Explora cómo cambian tu retiro las aportaciones, el tiempo y las comisiones. Compara posibilidades, no promesas.</p>{plan ? <SimulatorContent key={JSON.stringify(values)} plan={plan} initial={initial}/> : <section className="mt-7 rounded-3xl border bg-card p-8 text-center"><h2 className="text-xl font-semibold">Necesitamos tus datos para proyectar</h2><p className="mt-3 text-sm text-muted-foreground">Completa tu saldo, presupuesto y horizonte de retiro. No usamos datos de ejemplo.</p><Button asChild className="mt-5 h-12 rounded-xl"><Link to="/datos">Completar mis datos</Link></Button></section>}</main></div>;
}

function SimulatorContent({ plan, initial }: { plan: Plan; initial: number }) {
  const defaults: Fields = { monthly: String(initial), retirementAge: String(plan.retirementAge), annualReturn: '5', inflation: '3', annualFee: '0.5', retirementYears: '20' };
  const [fields, setFields] = useState<Fields>(defaults);
  const [nominal, setNominal] = useState(false);
  const [comparisons, setComparisons] = useState<Comparison[]>([]);
  const [notice, setNotice] = useState('');
  const update = (key: keyof Fields, value: string) => { setFields(previous => ({ ...previous, [key]: value })); setNotice(''); };
  const input: ScenarioInput = { balance: plan.balance, age: plan.age, monthly: Number(fields.monthly), retirementAge: Number(fields.retirementAge), annualReturn: Number(fields.annualReturn) / 100, inflation: Number(fields.inflation) / 100, annualFee: Number(fields.annualFee) / 100, retirementYears: Number(fields.retirementYears) };
  const result = Object.values(fields).every(value => value.trim() !== '') && Number.isSafeInteger(input.monthly) ? projectScenario(input) : null;
  const affordable = input.monthly <= plan.suggestion;
  // The base uses identical assumptions and horizon, isolating contribution changes.
  const baseline = result ? projectScenario({ ...input, monthly: initial }) : null;
  const rows = result && baseline ? result.rows.map((row, index) => ({ age: row.age, scenario: nominal ? row.nominal : row.real, current: nominal ? baseline.rows[index].nominal : baseline.rows[index].real, noFee: nominal ? row.grossReal * Math.pow(1 + input.inflation, row.age - plan.age) : row.grossReal })) : [];
  const addComparison = () => {
    if (!result || !baseline || !affordable || comparisons.length >= 3) return;
    setComparisons(previous => [...previous, { id: Date.now(), fields: { ...fields }, real: result.real, income: result.monthlyIncome, delta: result.real - baseline.real }]);
    setNotice('Escenario añadido a la comparación temporal. No se ha guardado en una cuenta.');
  };
  const controls: { key: keyof Fields; label: string; min: number; max: number; step: number; help: string }[] = [
    { key: 'monthly', label: 'Aportación mensual (MXN)', min: 0, max: 1e9, step: 1, help: `Pesos completos. Límite de presupuesto: ${mxn(plan.suggestion)}/mes.` },
    { key: 'retirementAge', label: 'Edad de retiro', min: plan.age + 1, max: 90, step: 1, help: `Edad actual: ${plan.age} años. El horizonte cambia al ajustar esta edad.` },
    { key: 'annualFee', label: 'Comisión anual sobre saldo (%)', min: 0, max: 5, step: 0.01, help: '0.50% es un supuesto ilustrativo, no la tarifa verificada de tu AFORE.' },
    { key: 'annualReturn', label: 'Rendimiento bruto anual (%)', min: -20, max: 20, step: 0.1, help: 'Antes de descontar la comisión. También puedes probar rendimientos negativos.' },
    { key: 'inflation', label: 'Inflación anual (%)', min: 0, max: 15, step: 0.1, help: 'Se usa para expresar el poder de compra en pesos de hoy.' },
    { key: 'retirementYears', label: 'Años que durará el retiro', min: 5, max: 40, step: 1, help: 'Distribuimos el capital entre estos años, sin rendimiento durante el retiro.' },
  ];
  return <>
    <div className="mt-6 flex gap-3 rounded-2xl border bg-secondary/40 p-4 text-xs leading-5"><Info size={18} className="shrink-0 text-primary"/><p><strong>Datos manuales, no verificados.</strong> El camino base usa {mxn(initial)}/mes, el monto recibido de la recomendación o la sugerencia si entraste directamente. No representa aportaciones reales. Nada se guarda; al salir se pierden ajustes y comparaciones.</p></div>
    <div className="mt-6 grid items-start gap-6 lg:grid-cols-[0.8fr_1.5fr]">
      <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">Prueba un escenario</h2><Button variant="ghost" size="icon" aria-label="Restablecer supuestos iniciales" onClick={() => { setFields(defaults); setNotice('Supuestos restablecidos.'); }} className="h-11 w-11 rounded-xl"><RotateCcw size={17}/></Button></div><div className="mt-4 space-y-6">{controls.map(control => <div key={control.key} className="space-y-2"><Label htmlFor={control.key}>{control.label}</Label><Input id={control.key} type="number" inputMode={control.step === 1 ? 'numeric' : 'decimal'} value={fields[control.key]} min={control.min} max={control.max} step={control.step} onChange={event => update(control.key, event.target.value)} aria-describedby={`${control.key}-help`} className="h-12 rounded-xl text-base"/>{(control.key === 'monthly' || control.key === 'retirementAge' || control.key === 'annualFee') && <Slider aria-label={control.label} min={control.min} max={control.key === 'monthly' ? Math.max(1, plan.suggestion) : control.max} step={control.step} disabled={control.key === 'monthly' && plan.suggestion === 0} value={[Math.max(control.min, Math.min(control.key === 'monthly' ? plan.suggestion : control.max, Number(fields[control.key]) || 0))]} onValueChange={([value]) => update(control.key, String(value))} className="py-3"/>}<p id={`${control.key}-help`} className="text-xs leading-5 text-muted-foreground">{control.help}</p></div>)}</div><p className="mt-5 rounded-xl bg-muted p-3 text-xs leading-5 text-muted-foreground">La comisión se descuenta del saldo invertido, no se añade a tu gasto mensual. No altera el límite de aportación de tu presupuesto.</p></section>
      <div className="min-w-0 space-y-6">
        {!result || !baseline ? <div role="status" className="rounded-2xl bg-[hsl(var(--warning))] p-5 text-sm leading-6 text-[hsl(var(--warning-foreground))]">Completa todos los campos dentro de sus rangos: aporte de 0 a 1,000,000,000 en pesos completos; retiro posterior a tu edad actual y hasta 90 años; comisión de 0 a 5%; rendimiento de −20 a 20%; inflación de 0 a 15%; duración de 5 a 40 años completos.</div> : <>
          {!affordable && <div role="status" className="rounded-2xl bg-[hsl(var(--warning))] p-4 text-sm leading-6 text-[hsl(var(--warning-foreground))]"><strong>Este aporte supera tu límite orientativo de {mxn(plan.suggestion)}.</strong><p>Mostramos el resultado solo para explorar, no como recomendación. No puedes añadirlo a la comparación hasta elegir un monto dentro del límite. No cambiamos tu entrada automáticamente.</p><Button variant="outline" className="mt-3 h-11 rounded-xl" onClick={() => update('monthly', String(plan.suggestion))}>Elegir {mxn(plan.suggestion)}/mes</Button></div>}
          {plan.available <= 0 && <p className="rounded-xl bg-secondary p-4 text-sm leading-6 text-primary">Tu presupuesto no tiene disponible positivo. Prioriza revisar ingresos y compromisos antes de aportar. Puedes explorar con $0.</p>}
          <section className="rounded-3xl border bg-card p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-lg font-semibold">El tiempo y los costos sí importan</h2><p className="mt-1 text-xs text-muted-foreground">Proyección a los {input.retirementAge} años · {input.retirementAge - plan.age} años por delante</p></div><div className="flex rounded-xl bg-muted p-1">{[false, true].map(value => <button key={String(value)} onClick={() => setNominal(value)} aria-pressed={value === nominal} className={`min-h-10 rounded-lg px-3 text-xs font-semibold ${value === nominal ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>{value ? 'Pesos futuros' : 'Pesos de hoy'}</button>)}</div></div><ScenarioChart rows={rows} nominal={nominal}/><p className="mt-4 text-xs leading-5 text-muted-foreground">Base y escenario usan la misma edad de retiro, rendimiento, inflación y comisión elegidos. Solo cambia el aporte: {mxn(initial)} frente a {mxn(input.monthly)}/mes. {nominal ? 'Importes nominales, sin descontar inflación.' : 'Importes ajustados por inflación.'}</p></section>
          <section aria-label="Resultados del escenario" className="grid gap-3 sm:grid-cols-2">{[
            ['Saldo proyectado neto', mxn(nominal ? result.nominal : result.real), nominal ? 'Pesos futuros, después de comisión.' : 'Pesos de hoy, después de comisión.'],
            ['Ingreso mensual estimado', mxn(result.monthlyIncome), `Siempre en pesos de hoy, distribuido en ${input.retirementYears} años.`],
            ['Cambio frente al camino base', mxn((nominal ? result.nominal - baseline.nominal : result.real - baseline.real)), 'Comparación con los mismos supuestos y horizonte.'],
            ['Impacto total de la comisión', mxn(nominal ? result.feeImpactNominal : result.feeImpactReal), 'Menor saldo final: comisiones más el crecimiento que dejan de generar.'],
          ].map(([title, value, hint]) => <article key={title} className="min-w-0 rounded-2xl border bg-card p-5"><h3 className="text-xs text-muted-foreground">{title}</h3><p className="mt-3 break-words text-2xl font-semibold text-primary">{value}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{hint}</p></article>)}</section>
          <section className="rounded-3xl bg-primary p-6 text-primary-foreground"><h2 className="font-editorial text-2xl">Una comisión pequeña también cuenta.</h2><p className="mt-3 text-sm leading-6">Con {fields.annualFee}% anual, las comisiones descontadas sumarían {mxn(result.totalFeesNominal)} en pesos nominales de cada mes. Esta suma no es el impacto final: también se pierde crecimiento sobre lo descontado.</p><p className="mt-3 text-xs leading-5">Modelo simplificado: cada mes el saldo crece por (1 + rendimiento anual)^(1/12), se descuenta comisión anual ÷ 12 sobre ese saldo y luego entra la aportación. No es el método contractual verificado de ningún proveedor.</p></section>
          <Button onClick={addComparison} disabled={!affordable || comparisons.length >= 3} className="h-12 w-full rounded-xl"><Plus size={17} className="mr-2"/>{comparisons.length >= 3 ? 'Máximo de 3 escenarios temporales' : 'Añadir a comparación temporal'}</Button>
        </>}
        <p role="status" className="text-sm text-primary">{notice}</p>
      </div>
    </div>
    <section className="mt-7 rounded-3xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-semibold">Tus posibilidades, lado a lado</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Hasta tres escenarios temporales. Todos los resultados de estas tarjetas están en pesos de hoy. El cambio usa el camino base con los mismos supuestos de cada tarjeta; edades distintas representan horizontes distintos.</p>{comparisons.length === 0 ? <p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Ajusta los controles y añade tu primer escenario.</p> : <div className="mt-5 grid gap-4 md:grid-cols-3">{comparisons.map((item, index) => <article key={item.id} className="min-w-0 rounded-2xl border bg-background p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Escenario {index + 1}</h3><Button variant="ghost" size="icon" aria-label={`Eliminar escenario ${index + 1}`} className="h-11 w-11 rounded-xl" onClick={() => setComparisons(previous => previous.filter(row => row.id !== item.id))}><Trash2 size={16}/></Button></div><p className="text-xs text-muted-foreground">{mxn(Number(item.fields.monthly))}/mes · Retiro a los {item.fields.retirementAge}</p><p className="mt-4 break-words text-2xl font-semibold text-primary">{mxn(item.real)}</p><p className="mt-1 text-xs">Ingreso: {mxn(item.income)}/mes</p><p className="mt-2 text-xs">Cambio vs. base: {mxn(item.delta)}</p><p className="mt-4 text-xs leading-5 text-muted-foreground">Comisión {item.fields.annualFee}% · Rendimiento {item.fields.annualReturn}% · Inflación {item.fields.inflation}% · Retiro de {item.fields.retirementYears} años</p><Button variant="outline" onClick={() => { setFields({ ...item.fields }); setNotice(`Escenario ${index + 1} cargado en los controles. Los cambios no modifican la tarjeta existente.`); }} className="mt-4 h-11 w-full rounded-xl">Explorar este escenario</Button></article>)}</div>}</section>
    <aside className="mt-6 rounded-2xl bg-secondary/50 p-5 text-xs leading-6 text-muted-foreground"><strong className="text-primary">Supuestos y límites.</strong> Aportaciones fijas al final de cada mes, sin aumentar con inflación. El ingreso de retiro divide el saldo real entre los meses de retiro y supone rendimiento y comisiones cero durante esa etapa. No se incluyen impuestos, beneficios fiscales, pensión pública, aportaciones patronales ni otros cargos. El saldo reportado no cambia. Las estimaciones no son rendimientos garantizados ni asesoría individualizada. Conexiones, guardado y pagos reales no están disponibles.</aside>
  </>;
}
