import { useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getDashboard, mxn } from "@/lib/finance/dashboard";

type Plan = NonNullable<ReturnType<typeof getDashboard>>;
export default function ProjectionChart({ plan }: { plan: Plan }) {
  const [nominal, setNominal] = useState(false);
  const rows = plan.rows.map(row => ({ ...row, baseline: nominal ? Math.round(row.baseline * Math.pow(1 + plan.inflation, row.age - plan.age)) : row.baseline, planned: nominal ? Math.round(row.planned * Math.pow(1 + plan.inflation, row.age - plan.age)) : row.planned }));
  return <section className="min-w-0 rounded-3xl border bg-card p-5 sm:p-7" aria-labelledby="projection-title"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="projection-title" className="text-lg font-semibold">Así podría crecer tu retiro</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Dos caminos para entender el efecto de la constancia.</p></div><div className="flex rounded-xl bg-muted p-1">{[false, true].map(value => <button key={String(value)} onClick={() => setNominal(value)} aria-pressed={nominal === value} className={`min-h-10 rounded-lg px-3 text-xs font-semibold ${nominal === value ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>{value ? 'Pesos futuros' : 'Pesos de hoy'}</button>)}</div></div>
    <p className="mt-5 text-xs text-muted-foreground">{nominal ? 'Valores nominales: sin descontar la inflación.' : 'Valores reales: ajustados por una inflación supuesta del 3% anual.'}</p>
    <div className="mt-5 h-64 w-full sm:h-72" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{ top: 10, right: 12, left: 0, bottom: 10 }}><CartesianGrid stroke="hsl(var(--border))" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="age" tickLine={false} axisLine={false} minTickGap={30} tick={{ fontSize: 11 }} tickFormatter={value => `${value} años`}/><YAxis width={58} tickLine={false} axisLine={false} tick={{ fontSize: 11 }} tickFormatter={value => new Intl.NumberFormat('es-MX', { notation: 'compact', maximumFractionDigits: 1 }).format(value)}/><Tooltip formatter={(value: number) => mxn(value)} labelFormatter={value => `A los ${value} años`} contentStyle={{ borderRadius: 16, borderColor: 'hsl(var(--border))' }}/><Line name="Con aportación sugerida" dataKey="planned" type="monotone" stroke="hsl(var(--primary))" strokeWidth={3} dot={false} isAnimationActive={false}/><Line name="Sin nuevas aportaciones" dataKey="baseline" type="monotone" stroke="hsl(var(--chart-muted))" strokeWidth={2} strokeDasharray="5 5" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
    <div className="flex flex-wrap gap-x-5 gap-y-2 text-xs"><span className="flex items-center gap-2"><span className="h-1 w-5 rounded bg-primary"/>Con {mxn(plan.suggestion)}/mes</span><span className="flex items-center gap-2 text-muted-foreground"><span className="w-5 border-t-2 border-dashed border-[hsl(var(--chart-muted))]"/>Sin nuevas aportaciones</span></div>
    <p className="mt-4 rounded-xl bg-secondary/50 p-3 text-xs leading-5">A los {plan.retirementAge} años: <strong>{mxn(rows[rows.length - 1].planned)}</strong> con la sugerencia, frente a <strong>{mxn(rows[rows.length - 1].baseline)}</strong> sin nuevas aportaciones. {nominal ? 'Importes en pesos futuros.' : 'Importes en pesos de hoy.'}</p>
    <details className="mt-4 text-xs"><summary className="cursor-pointer py-2 font-medium text-primary">Ver datos de la gráfica</summary><div className="mt-2 max-h-56 overflow-auto"><table className="w-full text-left"><caption className="sr-only">Proyección por edad en {nominal ? 'pesos futuros' : 'pesos de hoy'}</caption><thead><tr><th className="p-2">Edad</th><th className="p-2">Sin aportación</th><th className="p-2">Con sugerencia</th></tr></thead><tbody>{rows.map(row => <tr key={row.age} className="border-t"><th className="p-2 font-normal">{row.age}</th><td className="p-2">{mxn(row.baseline)}</td><td className="p-2">{mxn(row.planned)}</td></tr>)}</tbody></table></div></details>
  </section>;
}
